// Code generated by Kitex v0.4.2. DO NOT EDIT.

package feedservice

import (
	"context"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	feed "github.com/lius0712/douyin_server/kitex_gen/feed"
	proto "google.golang.org/protobuf/proto"
)

func serviceInfo() *kitex.ServiceInfo {
	return feedServiceServiceInfo
}

var feedServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FeedService"
	handlerType := (*feed.FeedService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetUserFeed": kitex.NewMethodInfo(getUserFeedHandler, newGetUserFeedArgs, newGetUserFeedResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "feed",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.4.2",
		Extra:           extra,
	}
	return svcInfo
}

func getUserFeedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(feed.FeedRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(feed.FeedService).GetUserFeed(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *GetUserFeedArgs:
		success, err := handler.(feed.FeedService).GetUserFeed(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserFeedResult)
		realResult.Success = success
	}
	return nil
}
func newGetUserFeedArgs() interface{} {
	return &GetUserFeedArgs{}
}

func newGetUserFeedResult() interface{} {
	return &GetUserFeedResult{}
}

type GetUserFeedArgs struct {
	Req *feed.FeedRequest
}

func (p *GetUserFeedArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(feed.FeedRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetUserFeedArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetUserFeedArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetUserFeedArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in GetUserFeedArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserFeedArgs) Unmarshal(in []byte) error {
	msg := new(feed.FeedRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserFeedArgs_Req_DEFAULT *feed.FeedRequest

func (p *GetUserFeedArgs) GetReq() *feed.FeedRequest {
	if !p.IsSetReq() {
		return GetUserFeedArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserFeedArgs) IsSetReq() bool {
	return p.Req != nil
}

type GetUserFeedResult struct {
	Success *feed.FeedResponse
}

var GetUserFeedResult_Success_DEFAULT *feed.FeedResponse

func (p *GetUserFeedResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(feed.FeedResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetUserFeedResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetUserFeedResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetUserFeedResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in GetUserFeedResult")
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserFeedResult) Unmarshal(in []byte) error {
	msg := new(feed.FeedResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserFeedResult) GetSuccess() *feed.FeedResponse {
	if !p.IsSetSuccess() {
		return GetUserFeedResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserFeedResult) SetSuccess(x interface{}) {
	p.Success = x.(*feed.FeedResponse)
}

func (p *GetUserFeedResult) IsSetSuccess() bool {
	return p.Success != nil
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetUserFeed(ctx context.Context, Req *feed.FeedRequest) (r *feed.FeedResponse, err error) {
	var _args GetUserFeedArgs
	_args.Req = Req
	var _result GetUserFeedResult
	if err = p.c.Call(ctx, "GetUserFeed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
